### ISSUE TITLE
Bug: file upload is broken in self-hosting variant

### ISSUE THREAD

**Issue by akurdyukov** [NancyFx/Nancy#1092]
I got exception
```
System.NotSupportedException: This stream does not support seek operations.
   at System.Net.HttpRequestStream.set_Position(Int64 value)
   at Nancy.IO.RequestStream.MoveStreamContentsToFileStream() in C:\Users\alik_000\Development\src\Nancy\src\Nancy\IO\RequestStream.cs:line 436
   at Nancy.IO.RequestStream.MoveStreamOutOfMemoryIfExpectedLengthExceedSwitchLength(Int64 expectedLength) in C:\Users\alik_000\Development\src\Nancy\src\Nancy\IO\RequestStream.cs:line 418
   at Nancy.IO.RequestStream..ctor(Stream stream, Int64 expectedLength, Int64 thresholdLength, Boolean disableStreamSwitching) in C:\Users\alik_000\Development\src\Nancy\src\Nancy\IO\RequestStream.cs:line 67
   at Nancy.IO.RequestStream.FromStream(Stream stream, Int64 expectedLength, Int64 thresholdLength, Boolean disableStreamSwitching) in C:\Users\alik_000\Development\src\Nancy\src\Nancy\IO\RequestStream.cs:line 281
   at Nancy.IO.RequestStream.FromStream(Stream stream, Int64 expectedLength, Boolean disableStreamSwitching) in C:\Users\alik_000\Development\src\Nancy\src\Nancy\IO\RequestStream.cs:line 276
   at Nancy.Hosting.Self.NancyHost.ConvertRequestToNancyRequest(HttpListenerRequest request) in C:\Users\alik_000\Development\src\Nancy\src\Nancy.Hosting.Self\NancyHost.cs:line 188
   at Nancy.Hosting.Self.NancyHost.Process(HttpListenerContext ctx) in C:\Users\alik_000\Development\src\Nancy\src\Nancy.Hosting.Self\NancyHost.cs:line 275
```
in vanilla Nancy.Demo.Hosting.Self sample trying to upload file.

This simple patch fixed the problem
```
 src/Nancy/IO/RequestStream.cs | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/src/Nancy/IO/RequestStream.cs b/src/Nancy/IO/RequestStream.cs
index 4adeff0..5a73d79 100644
--- a/src/Nancy/IO/RequestStream.cs
+++ b/src/Nancy/IO/RequestStream.cs
@@ -433,7 +433,10 @@
                 return;
             }
 
-            this.stream.Position = 0;
+            if (this.stream.CanSeek)
+            {
+                this.stream.Position = 0;
+            }
             this.stream.CopyTo(targetStream, 8196);
             if (this.stream.CanSeek)
             {

```

**Comment by 06b** [comment]
Looks like #1090 was fixed and considering this is the same problem - can this issue be closed?

**Comment by khellang** [comment]
Fixed with https://github.com/NancyFx/Nancy/commit/68986b7d6a3fc79ef4d1bc43f3a6f619ff25d7d5 :smile:
