### ISSUE TITLE
Model Binding fails on abstract class even with blacklist

### ISSUE THREAD

**Issue by wilhen01** [NancyFx/Nancy#1574]
I have a resource type which contains a heterogenous collection of activities, where activities all inherit from a base abstract class. For illustrative purposes, something like this:

``` C#
public abstract class Activity
{
    public string ActivityProperty { get; set; }
}

public class Resource
{
    public string Property1 { get; set; }

    public string Property2 { get; set; }

    public IList<Activity> Activities { get; set; } 
}
```

When using this.Bind<>() I get an exception:

```
System.Reflection.TargetInvocationException occurred
  HResult=-2146232828
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
       at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
       at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
       at Nancy.ModelBinding.DefaultBodyDeserializers.JsonBodyDeserializer.Deserialize(String contentType, Stream bodyStream, BindingContext context)
       at Nancy.ModelBinding.DefaultBinder.DeserializeRequestBody(BindingContext context)
       at Nancy.ModelBinding.DefaultBinder.Bind(NancyContext context, Type modelType, Object instance, BindingConfig configuration, String[] blackList)
       at Nancy.ModelBinding.DynamicModelBinderAdapter.TryConvert(ConvertBinder binder, Object& result)
       at CallSite.Target(Closure , CallSite , Object )
       at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
       at Nancy.ModelBinding.ModuleExtensions.Bind[TModel](INancyModule module, String[] blacklistedProperties)
       at Linn.Events.Service.Modules.EventsModule.PostEvent(Object parameters) in C:\Projects\events\Service\Modules\EventsModule.cs:line 99
  InnerException: System.MissingMethodException
       HResult=-2146233069
       Message=Cannot create an abstract class.
       Source=mscorlib
       StackTrace:
            at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
            at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
            at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
            at System.Activator.CreateInstance(Type type, Boolean nonPublic)
            at Nancy.Json.JavaScriptSerializer.ConvertToObject(IDictionary`2 dict, Type type)
            at Nancy.Json.JavaScriptSerializer.ConvertToType(Type type, Object obj)
            at Nancy.Json.JavaScriptSerializer.ConvertToList(ArrayList col, Type type)
            at Nancy.Json.JavaScriptSerializer.ConvertToType(Type type, Object obj)
            at Nancy.Json.JavaScriptSerializer.ConvertToObject(IDictionary`2 dict, Type type)
            at Nancy.Json.JavaScriptSerializer.ConvertToType(Type type, Object obj)
            at Nancy.Json.JavaScriptSerializer.ConvertToType[T](Object obj)
            at Nancy.Json.JavaScriptSerializer.Deserialize[T](String input)
       InnerException: 
```

The same exception still gets thrown using blacklisting, either by string or lambda

```
var resource = this.Bind<Resource>("Activities");
var resource = this.Bind<Resource>(ignore => ignore.Activities);
```

I think this must be a bug, unless I'm missing something? I'm using Nancy 0.23.

**Comment by luisrudge** [comment]
I'm having this issue as well :( Even when I blacklist the property, it still fails to bind

**Comment by phillip-haydon** [comment]
Binding to an abstract class???  Stop that. We don't create proxy objects for binding to.

**Comment by luisrudge** [comment]
I'm binding to a concrete class which has a property with an abstract type as it's type. I'm trying to ignore this property, but it doesn't work.

**Comment by wilhen01** [comment]
@phillip-haydon I think my original post illustrates a perfectly legitimate example. As pointed out by @luisrudge we're actually trying to ignore the abstract type, not bind to it. Blacklisting properties shouldn't be dependent on their modifiers.

**Comment by phillip-haydon** [comment]
@wilhen01 ok, I understand now, I was in hospital reading through my Nancy emails so I didn't fully understand the initial problem. 

This MAY be solved with #2061
