### ISSUE TITLE
OPTIONS request times out

### ISSUE THREAD

**Issue by jeffbonhag** [NancyFx/Nancy#1598]
Hi, there!  My time with Nancy has been very pleasant so far -- many thanks for all your work.  I was trying to enable CORS in a Nancy app yesterday, but the HTTP OPTIONS requests kept timing out.  Upon further investigation, it looks like even a simple OPTIONS request times out.

To recreate:

1. Create New Solution
2. Select "Empty Web Application"
3. Add Packages "Nancy.Hosting.Aspnet" (which pulls in base Nancy)
4. Add a new file `HelloOptions.cs`:
```
using System;
using Nancy;

namespace Hello
{
	public class HelloOptions : NancyModule
	{
		public HelloOptions ()
		{
			Options ["/"] = _ => "OK";
		}
	}
}
```
5. Start the application
6. Test the endpoint:

        curl http://localhost:8080 -X OPTIONS

Expected result:

    "OK"

Actual result (timeout):

```
<!DOCTYPE html>
<html>
    <head>
        <title>A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;}
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

            <br><br>

            <b> Exception Details: </b>System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond<br><br>

            <b>Source Error:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code>

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.</code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Stack Trace:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

[SocketException (0x274c): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond]
   System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags) +114
   System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size) +700

[IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.]
   System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size) +934
   Mono.WebServer.Mono.WebServer2124797.XSPWorker.Read(Byte[] buffer, Int32 position, Int32 size) +70
   Mono.WebServer.BaseRequestBroker.Read(Int32 requestId, Int32 size, Byte[]&amp; buffer) +345
   Mono.WebServer.XSPWorkerRequest.ReadInput(Byte[] buffer, Int32 offset, Int32 size) +240
   Mono.WebServer.XSPWorkerRequest.ReadEntityBody(Byte[] buffer, Int32 size) +131
   System.Web.HttpRequest.GetEntireRawContent() +1125
   System.Web.HttpRequest.get_InputStream() +151
   System.Web.HttpRequestWrapper.get_InputStream() +41
   Nancy.Hosting.Aspnet.NancyHandler.CreateNancyRequest(HttpContextBase context) +1165
   Nancy.Hosting.Aspnet.NancyHandler.ProcessRequest(HttpContextBase context, AsyncCallback cb, Object state) +131
   Nancy.Hosting.Aspnet.NancyHttpRequestHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object state) +130
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +834
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +188
</pre></code>

                  </td>
               </tr>
            </table>

            <br>

            <hr width=100% size=1 color=silver>

            <b>Version Information:</b>&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.18446

            </font>

    </body>
</html>
<!--
[SocketException]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
[IOException]: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at Mono.WebServer.Mono.WebServer2124797.XSPWorker.Read(Byte[] buffer, Int32 position, Int32 size)
   at Mono.WebServer.BaseRequestBroker.Read(Int32 requestId, Int32 size, Byte[]& buffer)
   at Mono.WebServer.XSPWorkerRequest.ReadInput(Byte[] buffer, Int32 offset, Int32 size)
   at Mono.WebServer.XSPWorkerRequest.ReadEntityBody(Byte[] buffer, Int32 size)
   at System.Web.HttpRequest.GetEntireRawContent()
   at System.Web.HttpRequest.get_InputStream()
   at System.Web.HttpRequestWrapper.get_InputStream()
   at Nancy.Hosting.Aspnet.NancyHandler.CreateNancyRequest(HttpContextBase context)
   at Nancy.Hosting.Aspnet.NancyHandler.ProcessRequest(HttpContextBase context, AsyncCallback cb, Object state)
   at Nancy.Hosting.Aspnet.NancyHttpRequestHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
-->
```

I've only tested on xsp4 so far.  I'm using Xamarin Studio 5.1 on Windows.  Also, I can run a vanilla ASP.NET app with xsp4, and everything seems hunky-dory.

Thanks!

**Comment by MrTomWhite** [comment]
@jjchiw It looks like this got merged a while ago. Can we go ahead and close this issue? :smile_cat:

**Comment by phillip-haydon** [comment]
:) thanks @MrTomWhite

**Comment by jeffbonhag** [comment]
Thanks!

**Comment by MrTomWhite** [comment]
You're welcome! I'm just doing my part; every issue that gets closed is another issue that doesn't need to be dealt with in the future.
