### ISSUE TITLE
Asterisk in query string makes request hang due to ArgmentException in StaticContentConventionBuilder.BuildContentDelegate

### ISSUE THREAD

**Issue by rickardraysearch** [NancyFx/Nancy#1803]
When processing a request to an address like "http://example.com/foo/*/baz", the exception below appears. Could it be that the fix in issue #1141 should be applied to the other calls to Path.GetFilePath in StaticContentConventionBuilder.BuildContentDelegate too?

In the stack trace below, "pathAndRotPair.Path" has a value like "/foo/*/baz".

```
System.ArgumentException occurred
  HResult=-2147024809
  Message=Illegal characters in path.
  Source=mscorlib
  StackTrace:
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)
       at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
       at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
       at System.IO.Path.GetFullPath(String path)
       at Nancy.Conventions.StaticContentConventionBuilder.<>c__DisplayClass19.<BuildContentDelegate>b__e(ResponseFactoryCacheKey pathAndRootPair)
  InnerException: 
```

**Comment by horsdal** [comment]
Looking at the documentation `Path.GetInvalidPathChars` (https://msdn.microsoft.com/en-us/library/system.io.path.getinvalidpathchars(v=vs.110).aspx) the solution to #1141 does not seem to apply to asterix.

**Comment by rickardraysearch** [comment]
That is indeed odd. An ironpython session shows some strange results below, which seems to indicate that '>' is an invalid path char, but '*' is not. Supplying either to GetFullPath() however gives a "ValueError" (ArgumentException) with message "Illegal characters in path."

```
>>> System.Char.Parse('>') in System.IO.Path.GetInvalidPathChars()
True
>>> System.IO.Path.GetFullPath(">")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Illegal characters in path.
>>> System.Char.Parse('*') in System.IO.Path.GetInvalidPathChars()
False
>>> System.IO.Path.GetFullPath("*")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Illegal characters in path.
```

As far as I can tell though, the solution to #1141 does not look at GetInvalidPathChars, but rather wraps the GetFullPath calls in a try-catch, which ought to work in this case as well, right?

**Comment by horsdal** [comment]
Yeah but `GetFullPath` uses `GetInvalidPathChars` according to MSDN.

**Comment by rickardraysearch** [comment]
I agree, the documentation says so. However, I cannot see how that is of relevance to the exception. What are you getting at? The GetSafeFileName wraps GetFileName in a try-catch - and as far as I can tell, it seems reasonable to make a similar wrapping of GetFilePath for GetSafeFilePath to avoid hanging requests for urls with asterisks and question marks in them.

**Comment by horsdal** [comment]
That seems reasonable. Are you up for creating the PR?

**Comment by thecodejunkie** [comment]
@rickardraysearch @horsdal ping

**Comment by sergeykonkin** [comment]
Looks like it's been fixed in 1940ad6a76f6df10df1db6a41240a56d996fd0c5. Should this issue be closed then?
