### ISSUE TITLE
Issue with the Nancy.Demo.Caching example

### ISSUE THREAD

**Issue by samwa** [NancyFx/Nancy#1822]
Hi
I've downloaded the source from git just yesterday
running the example code Nancy.Demo.Caching and navigating to route /cached gives and internal server error
here it is
Error Details

Nancy.RequestExecutionException: Oh noes! ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Nancy.Responses.MaterialisingResponse.<.ctor>b__0(Stream stream) in c:\Users\samw\OneDrive\Projects\R&D\Nancy-master\src\Nancy\Responses\MaterialisingResponse.cs:line 46
   at Nancy.Demo.Caching.CachedResponse..ctor(Response response) in c:\Users\samw\OneDrive\Projects\R&D\Nancy-master\src\Nancy.Demo.Caching\CachedResponse.cs:line 26
   at Nancy.Demo.Caching.CachingBootstrapper.SetCache(NancyContext context) in c:\Users\samw\OneDrive\Projects\R&D\Nancy-master\src\Nancy.Demo.Caching\CachingBootstrapper.cs:line 71
   at Nancy.AfterPipeline.<>c__DisplayClass4.b__3(NancyContext ctx, CancellationToken ct) in c:\Users\samw\OneDrive\Projects\R&D\Nancy-master\src\Nancy\AfterPipeline.cs:line 150
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex) in c:\Users\samw\OneDrive\Projects\R&D\Nancy-master\src\Nancy\NancyEngine.cs:line 284

Does anyone know if I need to configure something to get this demo to work?

Cheers
Sam

**Comment by JeanTerblanche** [comment]
I'm getting the exact same error as [this SO post](http://stackoverflow.com/questions/25886923/materialisingresponse-throwing-nullreferenceexception-in-nancy-web-application), except I'm using SSVE

**Comment by JeanTerblanche** [comment]
I was able to reproduce it using [this gist](https://gist.github.com/jchannon/6fe235343fe2e5c1d845), Hosting.AspNet and a view called "Error".

**Comment by thecodejunkie** [comment]
Pushed #2019 to fix the issue reported by @samwa 

This problem can only happen if `StaticConfiguration.DisableErrorTraces` is explicitly set to `true` or if you are running in debug mode (nancy will detect that and set `DisableErrorTraces` value). Should be resolved when the fix is pulled in
