### ISSUE TITLE
HEAD request failed with return View (version > 0.21)

### ISSUE THREAD

**Issue by bangd** [NancyFx/Nancy#1881]
HEAD request works fine with return "string" or something
but 500 error code when I return View["name"] from module.

 Get["/"] = parameters =>
           {
                //return "meme"; //it works fine
                return View["index"]; // 500 error
            };

**Comment by bangd** [comment]
Nancy.Hosting.Aspnet
and here is nancy razor view

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>NancyApplication1</title>

    <style type="text/css">
        body {
            text-align: center;
        }
    </style>

</head>
<body>
    <img src="~/Content/nancy-logo.png" alt="Nancy logo" /><br />
    blah blah
</body>
</html>

**Comment by khellang** [comment]
OK, I think you need to give us more than that. There are hundreds running Nancy on the ASP.NET host returning views like that without getting 500 errors. Do you have a stack trace? Anything?

**Comment by bangd** [comment]
Unfortunately not, but I can attach the demo project here
![capture_nancy_head](https://cloud.githubusercontent.com/assets/9058042/6823161/81f6bc02-d2dd-11e4-9143-d5744319b2d2.JPG)

https://www.dropbox.com/s/7bdassxi4b14k1z/NancyApplication1.zip?dl=0

**Comment by bangd** [comment]
any lucky with my sample project above?

**Comment by khellang** [comment]
Haven't had time to test it yet. It would be super helpful if you could get a hold of a stack trace. You could try turning on request tracing and see if that gives anything.

**Comment by bangd** [comment]
at the moment, I can only get trace log info from xml file
<EventData>
  <Data Name="ContextId">{00000000-0000-0000-5E00-0080000000FB}</Data>
  <Data Name="ModuleName">ManagedPipelineHandler</Data>
  <Data Name="Notification">128</Data>
  <Data Name="HttpStatus">500</Data>
  <Data Name="HttpReason">Internal Server Error</Data>
  <Data Name="HttpSubStatus">0</Data>
  <Data Name="ErrorCode">0</Data>
  <Data Name="ConfigExceptionInfo"></Data>
 </EventData>

**Comment by bangd** [comment]
![capture_nancy_head](https://cloud.githubusercontent.com/assets/9058042/6835402/6354fa02-d332-11e4-8710-062420cd22c2.JPG)

**Comment by Crisfole** [comment]
This sounds more like an IIS issue.  Can you issue other non-GET/POST requests?

**Comment by bangd** [comment]
Yes, the problem is I can do HEAD request with version 0.21. and with version >0.21 no problem with HEAD request if I return string or json from Module. but when I return View[], I could not do HEAD request.

**Comment by bangd** [comment]
It also happens on my server, not just IIS express that I did testing

**Comment by bangd** [comment]
I also tried the sample project on different pc/mac. the problem was still persisted

**Comment by bangd** [comment]
This is detailed error
Event code: 3005 
Event message: An unhandled exception has occurred. 

 
Exception information: 
    Exception type: NullReferenceException 
    Exception message: Object reference not set to an instance of an object.
   at Nancy.Responses.MaterialisingResponse.<.ctor>b__0(Stream stream)
   at Nancy.HeadResponse.CheckAndSetContentLength(Response response)
   at Nancy.HeadResponse..ctor(Response response)
   at Nancy.Routing.DefaultRequestDispatcher.<>c__DisplayClass2.<Dispatch>b__1(Task`1 completedRouteTask)
   at Nancy.Helpers.TaskHelpers.WhenCompleted[T](Task`1 task, Action`1 onComplete, Action`1 onFaulted, Boolean execSync)
   at Nancy.Routing.DefaultRequestDispatcher.<>c__DisplayClass2.<Dispatch>b__0(Task`1 completedTask)
   at Nancy.Helpers.TaskHelpers.WhenCompleted[T](Task`1 task, Action`1 onComplete, Action`1 onFaulted, Boolean execSync)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.<>c__DisplayClass7.<InvokeRequestLifeCycle>b__5(Task`1 t)
   at Nancy.Helpers.TaskHelpers.WhenCompleted[T](Task`1 task, Action`1 onComplete, Action`1 onFaulted, Boolean execSync)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
   at Nancy.NancyEngine.HandleRequest(Request request, Func`2 preRequest, CancellationToken cancellationToken)
   at Nancy.NancyEngineExtensions.HandleRequest(INancyEngine nancyEngine, Request request, Func`2 preRequest, Action`1 onComplete, Action`1 onError, CancellationToken cancellationToken)
   at Nancy.Hosting.Aspnet.NancyHandler.ProcessRequest(HttpContextBase context, AsyncCallback cb, Object state)
   at Nancy.Hosting.Aspnet.NancyHttpRequestHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

 
 
Request information: 
    Request URL: http://localhost:12116/ 
    Request path: / 
    User host address: ::1 
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: dev-PC\dev 
 
Thread information: 
    Thread ID: 6 
    Thread account name: dev-PC\dev 
    Is impersonating: False 
    Stack trace:    at Nancy.Responses.MaterialisingResponse.<.ctor>b__0(Stream stream)
   at Nancy.HeadResponse.CheckAndSetContentLength(Response response)
   at Nancy.HeadResponse..ctor(Response response)
   at Nancy.Routing.DefaultRequestDispatcher.<>c__DisplayClass2.<Dispatch>b__1(Task`1 completedRouteTask)
   at Nancy.Helpers.TaskHelpers.WhenCompleted[T](Task`1 task, Action`1 onComplete, Action`1 onFaulted, Boolean execSync)
   at Nancy.Routing.DefaultRequestDispatcher.<>c__DisplayClass2.<Dispatch>b__0(Task`1 completedTask)
   at Nancy.Helpers.TaskHelpers.WhenCompleted[T](Task`1 task, Action`1 onComplete, Action`1 onFaulted, Boolean execSync)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.<>c__DisplayClass7.<InvokeRequestLifeCycle>b__5(Task`1 t)
   at Nancy.Helpers.TaskHelpers.WhenCompleted[T](Task`1 task, Action`1 onComplete, Action`1 onFaulted, Boolean execSync)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
   at Nancy.NancyEngine.HandleRequest(Request request, Func`2 preRequest, CancellationToken cancellationToken)
   at Nancy.NancyEngineExtensions.HandleRequest(INancyEngine nancyEngine, Request request, Func`2 preRequest, Action`1 onComplete, Action`1 onError, CancellationToken cancellationToken)
   at Nancy.Hosting.Aspnet.NancyHandler.ProcessRequest(HttpContextBase context, AsyncCallback cb, Object state)
   at Nancy.Hosting.Aspnet.NancyHttpRequestHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
 
 
Custom event details:

**Comment by lokki** [comment]
Apparently PreExecute does not get called on the MaterialisingResponse before it is used by the whatever HEAD response there is

**Comment by horsdal** [comment]
I have a repro for this. Will try track down the problem.
