### ISSUE TITLE
Self hosting fails in LinqPad

### ISSUE THREAD

**Issue by lance5107B** [NancyFx/Nancy#1891]
I am attempting to get Nancy running with self hosting in LinqPad.

```C#
using (var host = new NancyHost(new Uri("http://localhost:1234")))
{
	host.Start();
	Console.ReadLine();
}
```

However the above code results in:

```
Could not load file or assembly 'ICSharpCode.NRefactory, Version=3.0.0.3630, Culture=neutral, PublicKeyToken=efe927acf176eea2' or one of its dependencies. The system cannot find the file specified.
```

```
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.get_DeclaringType()
   at Nancy.TinyIoc.TinyIoCContainer.<AutoRegisterInternal>b__13(Type type)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Nancy.TinyIoc.TinyIoCContainer.AutoRegisterInternal(IEnumerable`1 assemblies, DuplicateImplementationActions duplicateAction, Func`2 registrationPredicate)
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.Initialise()
   at Nancy.Hosting.Self.NancyHost..ctor(INancyBootstrapper bootstrapper, HostConfiguration configuration, Uri[] baseUris)
   at UserQuery.Main()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

I know that LinqPad uses NRefactory internally and I think this may be causing a conflict.  I am not sure if this is something that should be fixed in Nancy or LinqPad ( if it can be fixed ).  Has anyone else experienced this and perhaps found a work around?

**Comment by pwhe23** [comment]
I just started looking into Nancy myself and ran into this just now. Any help?

**Comment by khellang** [comment]
It looks like it's the `DefaultNancyBootstrapper`'s auto-registration that's causing this. Try using a custom bootstrapper by deriving from `DefaultNancyBootstrapper` and overriding `ConfigureApplicationContainer` without calling the `base` method.

**Comment by pwhe23** [comment]
Thanks Kristian, that worked like a charm. This ran just fine in Linqpad:

```
//nuget Nancy
//nuget Nancy.Hosting.Self

void Main() {
	using (var host = new Nancy.Hosting.Self.NancyHost(new Uri("http://localhost:8080"), new MyNancyBootstrapper())) {
		host.Start();
		Console.ReadLine();
	} 
}

public class HelloModule : Nancy.NancyModule {
    public HelloModule()     {
        Get["/"] = parameters => "Hello World";
    }
}

public class MyNancyBootstrapper : Nancy.DefaultNancyBootstrapper {
	protected override void ConfigureApplicationContainer(Nancy.TinyIoc.TinyIoCContainer container) {
	}
}
```

**Comment by khellang** [comment]
Great! :grin:

**Comment by ryanfzy** [comment]
I ran into this issue as well. Thanks for the fix.
