### ISSUE TITLE
Too eager when looking for file name pattern

### ISSUE THREAD

**Issue by vchekan** [NancyFx/Nancy#1991]
I am requesting 

    GET http://localhost/taskrunner/main.js

My routes are:

            Get["/"] = _ => View["default.html"];
            Get["/main.js"] = _ => View["main.js"];

Yet I am getting an error:

<pre id="errorContents">Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.AmbiguousViewsException: This exception was thrown because multiple views were found. 2 view(s):
	/main.js
	/main.min.js
   at Nancy.ViewEngines.DefaultViewLocator.LocateAndCacheUncachedView(String viewName)
   at Nancy.ViewEngines.DefaultViewLocator.LocateView(String viewName, NancyContext context)
   at Nancy.ViewEngines.DefaultViewResolver.GetViewLocation(String viewName, Object model, ViewLocationContext viewLocationContext)
   at Nancy.ViewEngines.DefaultViewFactory.GetRenderedView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at Nancy.ViewEngines.DefaultViewFactory.RenderView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at Nancy.Responses.Negotiation.ViewProcessor.Process(MediaRange requestedMediaRange, Object model, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(IEnumerable`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.CreateResponse(IList`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(Object routeResult, NancyContext context)
   at Nancy.Routing.DefaultRouteInvoker.<>c__DisplayClassa.<Invoke>b__6(Task`1 completedTask)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)</pre>

Why does it consider "main.min.js" when it has been requested "main.js"? It is quite usual to have non minified and minified versions of a library in your path, especially during development.

**Comment by phillip-haydon** [comment]
Why are you attempting to return your HTML / JS like this? You're running them through the pipeline for no reason...

You either want to add them to the static content conventions:

https://github.com/NancyFx/Nancy/wiki/Managing-static-content

Or do something like:
```
return Response.AsFile("/statics/main.js")
                          .WithHeaders("Content-Type", "application/javascript");
```

**Comment by vchekan** [comment]
Yeah, I figured it out. Documentation is missing on this use case
