### ISSUE TITLE
Nancy throws exception when using c:\users\username\documents as the root path

### ISSUE THREAD

**Issue by toenuff** [NancyFx/Nancy#2146]
I have a getrootpath that looks like this:

```c#
    public class CustomRootPathProvider : IRootPathProvider
    {
        public string GetRootPath()
        {
            return @"c:\users\tome\documents";
        }
    }
```

It throws the following error at least in win 10.  It only does this with this root path that I can tell, but a few others are testing it with other paths.  We'll update this thread if there are others found.

```
.\NancyApplication2.exe : 
At line:1 char:1
+ .\NancyApplication2.exe 2>err.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Unhandled Exception: 
Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: Nancy.ViewEngines.ViewEngineApplicationStartup ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable 
to resolve type: Nancy.ViewEngines.DefaultViewLocator ---> System.UnauthorizedAccessException: Access to the path 'c:\users\tome\documents\My Music' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__1`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Nancy.ViewEngines.FileSystemViewLocationProvider.GetViewsFromPath(String path, IEnumerable`1 supportedViewExtensions)
   at Nancy.ViewEngines.DefaultViewLocator.GetInititialViewLocations()
   at Nancy.ViewEngines.DefaultViewLocator..ctor(IViewLocationProvider viewLocationProvider, IEnumerable`1 viewEngines)
   at lambda_method(Closure , Object[] )
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, 
ResolveOptions options)
   --- End of inner exception stack trace ---
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, 
ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions 
options)
   at Nancy.TinyIoc.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, 
ResolveOptions options)
   --- End of inner exception stack trace ---
   at Nancy.TinyIoc.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, 
ResolveOptions options)
   at Nancy.TinyIoc.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions 
options)
   at Nancy.TinyIoc.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__1`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.Initialise()
   at Nancy.Hosting.Self.NancyHost..ctor(INancyBootstrapper bootstrapper, HostConfiguration configuration, Uri[] baseUris)
   at NancyApplication2.Program.Main(String[] args) in c:\Users\Tome\Documents\Visual Studio 2013\Projects\NancyApplication2\NancyApplication2\Program.cs:line 13
```

**Comment by toenuff** [comment]
Actually, it appears to happen in any folder where there is a subfolder with no permissions.  It's also iterating through hidden folders.  For example, you can't use the root of your c-drive because the recycle bin usually has some access denied error.

I have a quick test in ps that I can do to determine if that is an acceptable path:
Get-ChildItem c:\users\tome\documents -Depth 1 -force -Recurse -ea stop

So, the question is whether or not this is the expected behavior or whether or not Nancy should be handling that and only returning 404 or 401 if access is denied to a path.

**Comment by thecodejunkie** [comment]
Yes? This is a Windows file system security thing. There's no way for us to bump the process up to admin privileges, nor should we :)

Possible workarounds

1. Don't use a restricted folder
2. Set the permissions on the restricted folder so the app has permission to read/write
3. Run your application as admin

**Comment by beatcracker** [comment]
It looks like Nancy can't follow symlinks (junctions), is it by design? Because in @toenuff 's example `c:\users\tome\documents\My Music` is a junction to `c:\users\tome\My Music` and it's fully accesible to the current user running nancy.

In my case, Nancy can't access `C:\Users\Administrator\Documents\My Music`, despite that I have full permissions for the target folder `C:\Users\Administrator\Music`.

    C:\Users\Administrator\Documents>dir /AL /S .\
     Volume in drive C is System
     Volume Serial Number is 70EB-8219

     Directory of C:\Users\Administrator\Documents

    17.12.2013  01:03    <JUNCTION>     My Music [C:\Users\Administrator\Music]
    17.12.2013  01:03    <JUNCTION>     My Pictures [C:\Users\Administrator\Pictures
    ]
    17.12.2013  01:03    <JUNCTION>     My Videos [C:\Users\Administrator\Videos]
                   0 File(s)              0 bytes

**Comment by khellang** [comment]
> It looks like Nancy can't follow symlinks (junctions), is it by design?

I doubt it's by design. It probably just hasn't been thought of.

I don't think Nancy does anything special to block or not follow symlinks. It's probably just a limitation of the .NET APIs. I don't think it's Nancy's fault that `Directory.GetFiles` throws that exception :smile: If you have any good suggestions, we'd :heart: to hear about them.

**Comment by xt0rted** [comment]
There's a similar question [on StackOverflow](http://stackoverflow.com/q/10477113/39605) about this issue ([here's the answer it points back to](http://stackoverflow.com/a/9882819/39605)).

By the looks of it you'll need to put some additional logic in there to check if the folder is a symlink, and if so use the location it points to instead.

Nancy not doing this for you might not be very [SDHP™](https://github.com/nancyFx/nancy#the-super-duper-happy-path), but it's just as easy to add this logic to your `IRootPathProvider` with a `Lazy<string>` if needed.

**Comment by beatcracker** [comment]
I've just re-checked and Nancy works fine with junctions. It's just that some of the Windows' junctions designed for backward compatibility have peculiar permissions set on them: they deny `Everyone` permissions to `List folder`/`read data`, probably to stop legacy applications from enumerating files via those junctions twice. You can read more about this here: [Windows Vista/Windows 7 Junctions (Access Denied “Problem”)](https://pherricoxide.wordpress.com/2009/11/07/windows-vistawindows-7-junctions-access-denied-problem/). 

I'm still not sure that accessing such folders should be a fatal exception and not just 401/3/4 code, but I'm out of my depth here, so it's up to you to decide.

**Comment by thecodejunkie** [comment]
It's been like this for nearly 5 years so I doubt it's a real hotspot for problems. Looking at the code that @xt0rted linked, it does look like a mouth full to handle and I don't even want to think about mono/*nix support. 

This is not going to be a high priority change for us, but if someone sends us a pull-request when we'll evaluate it there and then

**Comment by viliwonka** [comment]
I use Linux and I was pulling my hair out with this bullshit, so to save nerves of other poor soul in future: here is it:

-> Set your root directory - where Nancy EXE file is
-> Just run your Nancy with root permission: you need root anyway to have http listener at port 80
