### ISSUE TITLE
System.ArgumentNullException when application compiled into Release mode

### ISSUE THREAD

**Issue by tidusjar** [NancyFx/Nancy#2338]
Hello again!

I'm getting the following exception when I compile my application into release mode (on my dev machine). Running in Debug is fine...

```
Error Details

Nancy.RequestExecutionException: Oh noes! ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Nancy.ViewEngines.DefaultViewCache.GetOrAdd[TCompiledView](ViewLocationResult viewLocationResult, Func`2 valueFactory)
   at Nancy.ViewEngines.Razor.RazorViewEngine.GetOrCompileView(ViewLocationResult viewLocationResult, IRenderContext renderContext, Assembly referencingAssembly, Type passedModelType)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at CallSite.Target(Closure , CallSite , RazorViewEngine , ViewLocationResult , IRenderContext , Assembly , Object )
   at Nancy.ViewEngines.Razor.RazorViewEngine.GetViewInstance(ViewLocationResult viewLocationResult, IRenderContext renderContext, Assembly referencingAssembly, Object model)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at CallSite.Target(Closure , CallSite , RazorViewEngine , ViewLocationResult , IRenderContext , Assembly , Object )
   at Nancy.ViewEngines.Razor.RazorViewEngine.<>c__DisplayClass2b.b__2a(Stream stream)
   at Nancy.ViewEngines.Razor.HtmlHelpers.Partial(String viewName, Object modelForPartial)
   at Nancy.ViewEngines.Razor.HtmlHelpers.Partial(String viewName)
   at RazorOutput.RazorView.Execute()
   at Nancy.ViewEngines.Razor.NancyRazorViewBase`1.ExecuteView(String body, IDictionary`2 sectionContents)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at Nancy.ViewEngines.Razor.RazorViewEngine.<>c__DisplayClass2b.b__2a(Stream stream)
   at Nancy.Responses.MaterialisingResponse.PreExecute(NancyContext context)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```

Url: Localhost:xxxx/Admin

**AdminModule**

```
public class AdminModule : NancyModule
    {
        private ISettingsService<PlexRequestSettings> RpService { get; set; }
        private static Logger Log = LogManager.GetCurrentClassLogger();

        public AdminModule(ISettingsService<PlexRequestSettings> rpService) : base("admin")
        {
            RpService = rpService;

            this.RequiresAuthentication();

            Get["/"] = _ => Admin();
        }

        private Negotiator Admin()
        {
            var settings = RpService.GetSettings();
            Log.Trace("Getting Settings:"); // This is logged

            return View["/Settings", settings];
        }
```

What I don't understand is that it works in debug...
Here is the view: https://github.com/tidusjar/PlexRequests.Net/blob/master/PlexRequests.UI/Views/Admin/Settings.cshtml

I can't see anything wrong with the code that I wrote...

**Comment by jchannon** [comment]
Not sure if it will make a difference but try `return View["Settings", settings];`

**Comment by tidusjar** [comment]
Nope, still getting the same error :cry:

**Comment by tidusjar** [comment]
Does anyone have any idea? This is a bit of a deal breaker for me :disappointed: .

You can reproduce the issue with this project: https://github.com/tidusjar/PlexRequests.Net

Steps:
- Compile in Release
- Run `PlexRequests.exe`
- Enter a username on the first page
- Click login
- Register a new user
- Admin tab will appear
- Click on Admin and you will see the error. 

If you compile the application in `Debug` and follow the same steps this will not happen.

**Comment by khellang** [comment]
This probably works in debug because we automatically switch off view caching in debug mode. That's also why you're seeing

> Nancy.ViewEngines.DefaultViewCache.GetOrAdd[TCompiledView](ViewLocationResult viewLocationResult, Func`2 valueFactory)

I find it really weird that we haven't hit this error before. What version are you running on?

**Comment by khellang** [comment]
This;

> at Nancy.ViewEngines.Razor.HtmlHelpers.Partial(String viewName, Object modelForPartial)

tells me that it might be the call to `@Html.Partial("/Admin/_Sidebar")` that's failing. Could you try changing it to `@Html.Partial("_Sidebar")`?

**Comment by grumpydev** [comment]
Normally this happens when you use relative paths for views (../) that shouldn't work in debug but does, then fails in release.

**Comment by khellang** [comment]
It's a horrible experience, nevertheless, and we should fix it :smile:

**Comment by tidusjar** [comment]
That works! I would have expected `/Admin/_Sidebar` to work though.

Thanks for help again guys!

**Comment by khellang** [comment]
I'd like to keep this open to track a fix for the horrible experience when we can't find a view.

**Comment by tidusjar** [comment]
That makes sense!

**Comment by xt0rted** [comment]
@khellang #1281 has more info on how/why this happens but it was closed without a fix.

**Comment by tidusjar** [comment]
Was this fixed?

**Comment by thecodejunkie** [comment]
@tidusjar 

> I'd like to keep this open to track a fix for the horrible experience when we can't find a view.

This part we have not touched yet. It is out of scope for this issue atm and it is likely that the view engine sub-system will get a bigger overhaul post-2.0 (but not before). For instance it is quite possible that we will ditch out own Razor engine and integrate with the new one that was built for the latest version of ASP.NET
