### ISSUE TITLE
Binding nested list

### ISSUE THREAD

**Issue by OnamChilwan** [NancyFx/Nancy#2364]
Hi I have a model which looks like however when using the Bind<VoucherPayment>() it throws an exception however this only occurs when I am unit testing. If I hit it via the browser its fine and binds no problem.

**Version of Nancy.Testing 1.4.1**

```

    public class VoucherPayment
    {
        public VoucherPayment()
        {
        }

        public Address BillingAddress { get; set; }

        public List<Voucher> Vouchers { get; set; }
    }
```

The unit test looks like this:

```
            public void When_Creating_A_Voucher_Payment()
            {
                var browser = new Browser(
                    with =>
                    {
                        with.AllDiscoveredModules();
                        with.ResponseProcessor<JsonProcessor>();
                    });

                var body = new VoucherPayment
                {
                    Vouchers = new List<Voucher>(),
					BillingAddress = null
                };                

                var s = new CsQuery.Utility.JsonSerializer().Serialize(body);
                this.result = browser.Put($"foo/bar",
                    with =>
                    {
                        with.HttpRequest();
                        with.Header("Content-Type", "application/json");
                        with.Header("Accept", "application/json");
                        with.Body(s);
                    });
            }
```

Exception stack trace
   at Nancy.ModelBinding.DefaultBinder.Bind(NancyContext context, Type modelType, Object instance, BindingConfig configuration, String[] blackList)
   at Nancy.ModelBinding.DynamicModelBinderAdapter.TryConvert(ConvertBinder binder, Object& result)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Vouchers.Rest.Api.Modules.VouchersModule.AddPaymentIntent(Guid paymentReference) in C:\_VSO\Vouchers\Vouchers.Rest.Api\Modules\VouchersModule.cs:line 43
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Vouchers.Rest.Api.Modules.VouchersModule.<.ctor>b__2_0(Object args) in C:\_VSO\Vouchers\Vouchers.Rest.Api\Modules\VouchersModule.cs:line 27
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

Inner exception stack trace

   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at Nancy.Json.JavaScriptSerializer.ConvertToObject(IDictionary`2 dict, Type type)
   at Nancy.Json.JavaScriptSerializer.ConvertToObject(IDictionary`2 dict, Type type)
   at Nancy.Json.JavaScriptSerializer.ConvertToList(ArrayList col, Type type)
   at Nancy.Json.JavaScriptSerializer.ConvertToObject(IDictionary`2 dict, Type type)
   at Nancy.Json.JavaScriptSerializer.ConvertToType[T](Object obj)

**Comment by jchannon** [comment]
Can you try by removing the response processor. Remove the csquery and
header additions and use with.JsonBody(body); and see what you get. Either
way it shouldn't throw. It probably won't bind either though as I don't
think property based list binding is supported.

**Comment by OnamChilwan** [comment]
If this isn't supported how do people get around this issue? Custom binding?

**Comment by jchannon** [comment]
It depends on what you are doing see here https://github.com/NancyFx/Nancy/wiki/Model-binding#model-binding-against-lists

However in the past I have called Bind twice:

```
var person = this.Bind<Person>();
var addresses = this.Bind<List<Address>>();
person.Addresses = addresses;
```

**Comment by OnamChilwan** [comment]
The odd thing is when I run the application via IIS Express and hit the api via a rest client it resolves fine, it seems something in the unit test  framework that is causing this issue. I rolled back some changes and used the DefaultNancyBootstrapper and still get the same problem.

@jchannon problem with me doing that, i.e. 2 separate binds would be to modify my production code for the sake of a test passing I don't like the sound of that.

Going to revert to an earlier version and check if it has always been a problem.

**Comment by OnamChilwan** [comment]
Realized the problem, I had models which were immutable (didn't have public sets) and this was the issue. The example I gave about was the root object but the nested types had private setters.
