### ISSUE TITLE
Basic "Hello world!" page not working

### ISSUE THREAD

**Issue by Trigary** [NancyFx/Nancy#2550]
I am unable to get a simple "Hello world!" page running, with this code provided in a tutorial:

```
using Mono.Unix;
using Mono.Unix.Native;
using Nancy.Hosting.Self;
using System;

namespace NancyApp {
    class Program {
        static void Main (string[] args) {
            string uri = "http://localhost:8888/";
            HostConfiguration hostconfig = new HostConfiguration ();
            hostconfig.UrlReservations = new UrlReservations () { CreateAutomatically = true };
            Console.WriteLine ("Starting Nancy on " + uri);
            // initialize an instance of NancyHost
            NancyHost host = new NancyHost (hostconfig, new Uri (uri));
            host.Start ();  // start hosting
            // check if we're running on mono
            if (Type.GetType ("Mono.Runtime") != null) {
                // on mono, processes will usually run as daemons - this allows you to listen
                // for termination signals (ctrl+c, shutdown, etc) and finalize correctly
                UnixSignal.WaitAny (new[] {
                    new UnixSignal(Signum.SIGINT),
                    new UnixSignal(Signum.SIGTERM),
                    new UnixSignal(Signum.SIGQUIT),
                    new UnixSignal(Signum.SIGHUP)
                });
            } else {
                Console.ReadLine ();
            }
            Console.WriteLine ("Stopping Nancy");
            host.Stop ();  // stop hosting
        }
    }
}
```

```
using Nancy;

namespace NancyApp {
    public class HelloModule: NancyModule {
        public HelloModule () {
            Get["/"] = parameters => "Hello world!";
        }
    }
}
```
It gives no error if I run this in the debugger, but I get a 404 not found Nancy image error (so the url, the nancy server is found). On the other hand, if I build this and run the exe, it gives me this error:
```
Unhandled Exception: System.TypeLoadException: Could not load type 'Nancy.Bootstrapper.NancyBootstrapperLocator' from
sembly 'Nancy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Nancy.Hosting.Self.NancyHost..ctor(HostConfiguration configuration, Uri[] baseUris)
   at NancyApp.Program.Main(String[] args) in C:\Users\Trigary\Desktop\Nancy\Nancy\Program.cs:line 15
```
I have cleared the obj and the debug folders, I have updated Nancy after this issue came up, I started "using" it today, so it wasn't working before.

- Nancy version: v1.4.3
- Nancy host: Self-Hosted (v1.4.1)
- OS: Windows 10
- IDE: Microsoft Windows Visual Studio 2015 Community
- .NET Framework version: 4.5.2

**Comment by Trigary** [comment]
There was probably an error with the file handling (as I was trying to get it work, it didn't accept the nancy namespace now, that's why I think that was the issue back then as well), the module class is now in the same file (I have tried this as well before posting this issue, but that gave me an error at that time) and it works (I have made a new solution, escaped from the static function, if that helps someone). I'm sorry for the inconvenience.
