### ISSUE TITLE
Exception in AppDomainAssemblyCatalog

### ISSUE THREAD

**Issue by eeybye** [NancyFx/Nancy#2553]
### Description
Having non .Net dll's in folder causes a BadImageFormatException and FileLoadException in AppDomainAssemblyCatalog on line where inspectionAppDomain is loading assemblies.

### Steps to Reproduce
Simply copy win 32/64 native dlls to location for application.

### System Configuration
Windows 7 64bit Pro.
.NET framework 4.6.1

Nancy version: 2.0.0-barneyrubble
Selfhosting.

**Comment by thecodejunkie** [comment]
Thanks, can you provide a stack trace as well?

**Comment by khellang** [comment]
Shouldn't that be a reflection only load?

**Comment by eeybye** [comment]
Yes, that's the failing line.

Regards,
Erling

**Comment by jeblackburn** [comment]
I'm seeing something similar (same idea, different exception). I'm wondering why these assemblies were included in the collection returned by the call to GetLoadedNancyReferencingAssemblies that precedes this call. They certainly aren't NancyReferencing...

Here's a stacktrace:

10262 [1] ERROR Default (null) - error starting service, disposing container
System.IO.FileLoadException: Could not load file or assembly 'msvcm80.dll' or one of its dependencies. A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)
File name: 'msvcm80.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Runtime Assembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.AppDomain.Load(AssemblyName assemblyRef)
   at System.AppDomain.Load(AssemblyName assemblyRef)
   at Nancy.AppDomainAssemblyCatalog.LoadNancyReferencingAssemblies(IEnumerable`1 loadedAssemblies)
   at Nancy.AppDomainAssemblyCatalog.GetAvailableAssemblies()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Nancy.DefaultTypeCatalog.GetTypesAssignableTo(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Nancy.DefaultTypeCatalog.GetTypesAssignableTo(Type type, TypeResolveStrategy strategy)
   at Nancy.Bootstrapper.NancyInternalConfiguration.<>c.get_Default>b__1_0(ITypeCatalogtypeCatalog)
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.GetInitializedInternalConfiguration()
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.Initialise()
   at Nancy.Hosting.Self.NancyHost..ctor(INancyBootstrapper bootstrapper, HostConfiguration configuration, Uri[] baseUris
)

**Comment by thecodejunkie** [comment]
@khellang yeah that's what I'm thinking as well and why I thought that might be the culprit line 😄

**Comment by khellang** [comment]
It should probably still be (reflection-only) loaded like we do with the other assemblies, though; https://github.com/NancyFx/Nancy/blob/master/src/Nancy/AppDomainAssemblyCatalog.cs#L138-L149

**Comment by thecodejunkie** [comment]
@khellang you mean without loading into a temporary AppDomain?

**Comment by khellang** [comment]
No, it can still be loaded into a separate domain, but it should

- Swallow any exceptions and skip the assembly
- Instead of `AppDomain.CurrentDomain`, use `inspectionAppDomain`
- Instead of `Load`, use `ReflectionOnlyLoad`

:smile:

**Comment by thecodejunkie** [comment]
@khellang ahh, yeah that's what I had in mind.. got a bit confused by your previous comment and just making sure we're aligned 👍

**Comment by khellang** [comment]
BTW, `ReflectionOnlyLoad` doesn't take an `AssemblyName`, like `Load`, so we probably have to try `ReflectionOnlyLoad(string)`, where `string` is the `AssemblyName.FullName` :smile:

**Comment by thecodejunkie** [comment]
@khellang yes ;( consistent APIs yo!

**Comment by thecodejunkie** [comment]
Should be resolved by #2561

**Comment by valentin-turcu** [comment]
I'm hesitant to reopen this, but I'm having exactly the same issue running 2.0.0-clinteastwood.
![err](https://user-images.githubusercontent.com/6671776/30600030-a5328a4a-9d5e-11e7-86ab-f1444bfd9962.jpg)

I've got several native assemblies in my executable folder (this one is from the CEF project) and getting the same exception for each of them.
