### ISSUE TITLE
Nancy.ViewEngines.ViewNotFoundException:  With some clients.

### ISSUE THREAD

**Issue by iaanlouw** [NancyFx/Nancy#2632]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Hi, 

I am quite new to Nancy. 

I have encountered an issue where some clients works fine, where it seems some of the older clients are throwing this Nancy.ViewEngines.ViewNotFoundException.    I am sending the same payload to my Nancy App, but the older type of clients seems to induce the View not found exception. 

I have used a TCP proxy to capture traffic moving to/from the application and attached it here... fist the successful transaction and then the failed one.   

I have searched for something where the Exception occurs based on the client connecting but I cannot. 

If I am doing something wrong please let me know.

### Steps to Reproduce

First the output of the request (giving the desired feedback ) 

```
23/11/2016 15:00:39.919; Resolving Remote Host
23/11/2016 15:00:39.932; Remote Host resolved to 127.0.0.1
23/11/2016 15:00:39.932; Local Port (9956) opened
23/11/2016 15:00:39.932; Waiting for connections
23/11/2016 15:00:41.669; 980: Client connected; 127.0.0.1:59726
23/11/2016 15:00:41.669; 980: Connecting to Server
23/11/2016 15:00:41.670; 980: Connected to Server
23/11/2016 15:00:41.675; 980: Client to Server (409 bytes)
POST /json/reply/PaymentRequest HTTP/1.1
Host: localhost:9955
Connection: keep-alive
Content-Length: 122
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
Origin: chrome-extension://cokgbflfommojglbmbpenpphppikmonn
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8

23/11/2016 15:00:41.680; 980: Client to Server (122 bytes)
{"TillNo":1,"SiteId":"XXXX","OperatorCode":1,"Amount":6800,"Cashback":0,"Reference":"007220","ReceiptType":"escpos"}
23/11/2016 15:00:41.743; 980: Server to Client (228 bytes)
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Vary: Accept
Server: Microsoft-HTTPAPI/2.0
Link: </PaymentRequest.xml>; rel="application/xml"
Date: Wed, 23 Nov 2016 13:00:41 GMT

23/11/2016 15:00:41.745; 980: Server to Client (297 bytes)
11d
{"TillNo":1,"OperatorCode":1,"Amount":6800,"Cashback":0,"Reference":"007220","ResponseCode":"104","ResponseDesc":"Unknown Till No or Site ID","CardNo":null,"CardType":null,"ReceitpTextPlain":null,"ReceiptTextEpsonEsc":null,"ReceiptTextCustom":null,"ReceiptLines":null,"OtherData":null}
0
```

AND NOW FOR THE CLIENT THAT GETS THE FAILURE (using Delphi7 with Indy to make the request)

```
23/11/2016 15:36:38.479; Resolving Remote Host
23/11/2016 15:36:38.489; Remote Host resolved to 127.0.0.1
23/11/2016 15:36:38.489; Local Port (9956) opened
23/11/2016 15:36:38.489; Waiting for connections
23/11/2016 15:36:43.721; 1020: Client connected; 127.0.0.1:60081
23/11/2016 15:36:43.721; 1020: Connecting to Server
23/11/2016 15:36:43.721; 1020: Connected to Server
23/11/2016 15:36:43.723; 1020: Client to Server (219 bytes)
POST /json/reply/PaymentRequest HTTP/1.0
Connection: keep-alive
Content-Type: application/json
Content-Length: 121
Host: localhost:9955
Accept: text/html, */*
User-Agent: Mozilla/3.0 (compatible; Indy Library)

23/11/2016 15:36:43.724; 1020: Client to Server (121 bytes, Incomplete last line)
{"TillNo":1,"SiteId":"VEXENDEMO","OperatorCode":1,"Amount":6800,"Cashback":0,"Reference":"007220","ReceiptType":"escpos"}
23/11/2016 15:36:43.838; 1020: Server to Client (150 bytes)
HTTP/1.1 500 Internal Server Error
Content-Type: text/html
Server: Microsoft-HTTPAPI/2.0
Date: Wed, 23 Nov 2016 13:36:43 GMT
Connection: close

23/11/2016 15:36:43.839; 1020: Server to Client (3 bytes)
0000  EF BB BF                                          ...             
23/11/2016 15:36:43.847; 1020: Server to Client (16336 bytes, Incomplete last line)
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <title>500</title>
  <style type="text/css">
  body {
    font: 13.34px Arial, Helvetica, Sans-Serif;
    margin:50px 0px; padding:0px;
    text-align:center;
  }
  
  h1 {
    font-size: 24px;
    font-weight: bold;
    margin: 0; 
    padding: 0;
  }
  
  #mainContainer {
    margin: 0px auto;
    width: 500px;
    text-align:left;
  }
  
  #errorContainer {
    width: 500px;
    background: url(data:image/png;base64,iVBORw0...uQmCC) no-repeat;
    height: 230px;
  }
  
  #errorImage {
    float: left;
    width: 119px;
    margin-top: 40px;
    margin-left: 40px;
  }
  
  #errorText {
      float: right;
      width: 280px;
      margin-top: 40px;
      margin-right: 40px;
  }

  #creditsContainer 
  {
    margin-top: -30px;
    margin-left: 40px;
    color: #999999
  }
  
  #creditsContainer a
  {
    color: #777777
  }
  
  #errorToggle
  {
    float:right;
  }
  
  #errorToggle a
  {
    color: #777777;
  }
  
  #errorDetails
  {
    width: 100%;
    margin: 24px;
    text-align: left;
    display: block;
  }
  
  .clear {
    clear: both;
    height: 0px;
    margin: 0;
    padding: 0;
    visibility: hidden;
  }
  
  code {
    margin: 0 2px;
    padding: 0 5px;
    border: 1px solid #ddd;
    background-color: #f8f8f8;
    border-radius: 3px;
  }
  </style>

  <!--[if lt IE 8]>
  <style type="text/css">
    #embeddedImage {
      visibility: hidden;
    }
  </style>
  <![endif]-->
  
  <script type="text/javascript">
    function ShowHideDetails() {
      var details =  document.getElementById('errorDetails');
      
      if (details.style.display == 'block') {
        details.style.display = 'none';
      } else {
        details.style.display = 'block';
      }
    }
  </script>
</head>
<body>
  <div id="mainContainer">
    <div id="errorContainer">
      <div id="errorImage">
        <img id="embeddedImage" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEU.......UVORK5CYII=" width="115" height="150">
      </div>
      <div id="errorText">
        <h1>500 - InternalServerError</h1>
        <p>Something went horribly, horribly wrong while servicing your request.</p>
        <p>We're sorry :-(</p>
      </div>
      <div class="clear"></div>
    </div>
    <div id="creditsContainer">
      <p>Graphics courtesy of the awesome <a href="http://theoatmeal.com/" target="_blank">Matthew Inman</a> </p>
    </div>
    <div id="errorToggle"><a href="javascript:ShowHideDetails();">Details</a></div>
    <div class="clear"></div>
  </div>
  <div id="errorDetails">
    <h2>Error Details</h2>
    <pre id="errorContents">Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'PaymentResponse'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views/Main/PaymentResponse-en-ZA,views/Main/PaymentResponse,Main/PaymentResponse-en-ZA,Main/PaymentResponse,views/PaymentResponse-en-ZA,views/PaymentResponse,PaymentResponse-en-ZA,PaymentResponse
Root path: C:\Users\Iaan\documents\visual studio 2013\Projects\VssWebServiceN\VssWebServiceN\bin\Debug
If you were expecting raw data back, make sure you set the 'Accept'-header of the request to correct format, for example 'application/json'
   at Nancy.ViewEngines.DefaultViewFactory.GetRenderedView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at CallSite.Target(Closure , CallSite , DefaultViewFactory , Object , Object , ViewLocationContext )
   at Nancy.ViewEngines.DefaultViewFactory.RenderView(String viewName, Object model, ViewLocationContext viewLocationContext)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at CallSite.Target(Closure , CallSite , IViewFactory , String , Object , ViewLocationContext )
   at Nancy.Responses.Negotiation.ViewProcessor.Process(MediaRange requestedMediaRange, Object model, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at CallSite.Target(Closure , CallSite , IResponseProcessor , String , Object , NancyContext )
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(IEnumerable`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.CreateResponse(IList`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(Object routeResult, NancyContext context)
   at Nancy.Routing.DefaultRouteInvoker.<>c__DisplayClassa.<Invoke>b__6(Task`1 completedTask)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)</pre>
  </div>
  <script type="text/javascript">
      var toggle = document.getElementById('errorToggle');
      var errorContents = document.getElementById('errorContents');
      
      if (errorContents.innerText == '') {
          toggle.style.display = 'none';
      }
  </script>
</body>
</html>
23/11/2016 15:36:43.879; 1020: Server disconnected
23/11/2016 15:36:43.880; 1020: Disconnected from Client


```

### System Configuration

- Nancy version:
- Nancy host
  - [ ] ASP.NET
  - [ ] OWIN
  - [x] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by khellang** [comment]
Are you actually expecting a view back? Or do you want it as JSON?

It looks like you're returning an instance of `PaymentResponse` from your module, and rely on content negotiation to decide whether a client accepts a view or a JSON payload.

If you're expecting a view to be rendered based on the `PaymentResponse` model, you need to make sure that Nancy can find that view. From the error message you can see that Nancy's tried to locate the view in the following places:

```
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views/Main/PaymentResponse-en-ZA,views/Main/PaymentResponse,Main/PaymentResponse-en-ZA,Main/PaymentResponse,views/PaymentResponse-en-ZA,views/PaymentResponse,PaymentResponse-en-ZA,PaymentResponse
Root path: C:\Users\Iaan\documents\visual studio 2013\Projects\VssWebServiceN\VssWebServiceN\bin\Debug
```

If you want Nancy to serve a view, it needs to be in one of the locations listed, under the root path, using one of the file extensions listed.

If you're _not_ expecting a view to be rendered, you should follow the error message:

> If you were expecting raw data back, make sure you set the 'Accept'-header of the request to correct format, for example 'application/json'

As you can see, the first request, which gave you JSON back, has an Accept-header with `*/*`, which means it'll automatically pick JSON, while the second request has `text/html, */*`, which means it'll prioritize HTML before JSON.

Now, if you _always_ want to serve either HTML or JSON, you can use `Response.AsJson(model)` (for JSON) or just return `View[model]` (for HTML).

**Comment by iaanlouw** [comment]
Thank you very much!  
I did not realize that this is important until now!

> > As you can see, the first request, which gave you JSON back, has an Accept-header with */*, which means it'll automatically pick JSON, while the second request has text/html, */*, which means it'll prioritize HTML before JSON.
> 
> Now, if you always want to serve either HTML or JSON, you can use Response.AsJson(model) (for JSON) or just return View[model] (for HTML).

This made all the difference.

Yes - I have a "class" called PaymentResponse.  Based on previous tutorials i just return the class, and Nancy did all the magic for me.   

public MainModule()
        {
            Nancy.Json.JsonSettings.RetainCasing = true;

            Post["/json/reply/PaymentRequest"] = _ =>
                {
PaymentResponse response = new PaymentResponse() { ResponseCode = "96", ResponseDesc = "Could not decode JSON!" };
... do more stuff to fill out all the properties of response... 

return response; 
   };
};


While I was at a client I was hitting the brick wall since their code "did not work" -
