### ISSUE TITLE
Nancy self hosting issue with big file size (static file)

### ISSUE THREAD

**Issue by fakoua** [NancyFx/Nancy#2639]
### Description
When I request big file (bigger than 1 MB) Nancy Self host fails to response, using the official source code I got the following error in the debug trace:

```
System.Net.HttpListenerException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at Nancy.Responses.GenericFileResponse.<>c__DisplayClass8_0.<GetFileContent>b__0(Stream stream) in C:\Users\user\Downloads\Nancy-master\Nancy-master\src\Nancy\Responses\GenericFileResponse.cs:line 62
   at Nancy.Hosting.Self.NancyHost.OutputWithDefaultTransferEncoding(Response nancyResponse, HttpListenerResponse response) in C:\Users\user\Downloads\Nancy-master\Nancy-master\src\Nancy.Hosting.Self\NancyHost.cs:line 353
   at Nancy.Hosting.Self.NancyHost.ConvertNancyResponseToResponse(Response nancyResponse, HttpListenerResponse response) in C:\Users\user\Downloads\Nancy-master\Nancy-master\src\Nancy.Hosting.Self\NancyHost.cs:line 341
   at Nancy.Hosting.Self.NancyHost.<Process>d__27.MoveNext() in C:\Users\user\Downloads\Nancy-master\Nancy-master\src\Nancy.Hosting.Self\NancyHost.cs:line 419
```

I'm using the following code:

Custom Bootstraper:

```

protected override void ConfigureConventions(NancyConventions nancyConventions)
        {
            base.ConfigureConventions(nancyConventions);
nancyConventions.StaticContentsConventions.AddDirectory("/dir/", @"C:\path\dir");
        }
```

Any small file under the directory "Dir" works properly, any big file fails.

Is there any limitation with Nancy Self Hosting?

Thanks

### Steps to Reproduce
Request any big file (bigger than 5MB) using Nancy Self Host

### System Configuration
N/A
- Nancy version: Latest (1.4.2.0)
- Nancy host
  - [x] Self-Hosted Latest( 1.4.1.0)

- Other Nancy packages and versions: N/A
- Environment (Operating system, version and so on): Windows 10 
- .NET Framework version:
- Additional information: N/A

**Comment by khellang** [comment]
I think you need to give us more code to look at. Are you, by any chance, starting and stopping the host during the lifetime of the application?
