### ISSUE TITLE
Assembly.GetEntryAssembly() is null when running on AWS Lambda

### ISSUE THREAD

**Issue by andymac4182** [NancyFx/Nancy#2692]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When running under dotnet core 1.0.1 GetEntryAssembly() returns null due to how AWS start the app. 

```
An exception was thrown when the constructor for type 'PreviewAspNetCoreWebAPI.LambdaEntryPoint' was invoked. Check inner exception for more details.: LambdaException


at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.Activator.CreateInstance(Type type)
Exception has been thrown by the target of an invocation.: TargetInvocationException
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()
Value cannot be null.
Parameter name: assembly: ArgumentNullException
at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
at Nancy.DependencyContextAssemblyCatalog..ctor()
at Nancy.Bootstrapper.NancyBootstrapperLocator.GetAvailableBootstrapperTypes()
at Nancy.Bootstrapper.NancyBootstrapperLocator.GetBootstrapperType()
at Nancy.Bootstrapper.NancyBootstrapperLocator.LocateBootstrapper()
at Nancy.Bootstrapper.NancyBootstrapperLocator.get_Bootstrapper()
at Nancy.Owin.NancyMiddleware.UseNancy(NancyOptions options)
at Nancy.Owin.DelegateExtensions.UseNancy(Action`1 builder, NancyOptions options)
at Microsoft.AspNetCore.Builder.OwinExtensions.UseOwin(IApplicationBuilder builder, Action`1 pipeline)
```

### Steps to Reproduce
Use nancy with the template project from https://aws.amazon.com/blogs/developer/running-serverless-asp-net-core-web-apis-with-amazon-lambda/

### System Configuration
AWS Lambda

- Nancy version: 2.0.0-clinteastwood
- Nancy host
  - [ ] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions:
- Environment (Operating system, version and so on): AWS Lambda
- .NET Framework version: dotnet core 1.0.1
- Additional information:

**Comment by thecodejunkie** [comment]
Hmm, could you try and set [NancyBootstrapperLocator.Bootstrapper](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/NancyBootstrapperLocator.cs#L23) explicitly, something like

```c#
NancyBootstrapperLocator.Bootstrapper = new DefaultNancyBootstrapper(); // replace with your bootstrapper type
```

and try that? Explicitly setting it, causes the `NancyBootstrapperLocator` to short-circuit and not perform auto-detection. Please let me know if that solves it

Not sure how to re-design the code to function unless you are explicit about it. We need to know the entry assembly in order to new up `Microsoft.Extensions.DependencyModel.DependencyContextLoader` and read the assembly references

**Comment by andymac4182** [comment]
I will give that a go tomorrow. 

It appears that AWS Lambda is using unmanaged code to start the core app if I am reading the documentation from MSDN correctly. 

```
The GetEntryAssembly method can return null when a managed assembly has been loaded from an unmanaged application. For example, if an unmanaged application creates an instance of a COM component written in C#, a call to the GetEntryAssembly method from the C# component returns null, because the entry point for the process was unmanaged code rather than a managed assembly.
```
https://msdn.microsoft.com/en-us/library/system.reflection.assembly.getentryassembly(v=vs.110).aspx

**Comment by andymac4182** [comment]
I just tried that and it fixed one error and now I get the below error. 

```
An exception was thrown when the constructor for type 'PreviewAspNetCoreWebAPI.LambdaEntryPoint' was invoked. Check inner exception for more details.: LambdaException


at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.Activator.CreateInstance(Type type)
Exception has been thrown by the target of an invocation.: TargetInvocationException
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()
Value cannot be null.
Parameter name: assembly: ArgumentNullException
at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
at Nancy.DependencyContextAssemblyCatalog..ctor()
at Nancy.Bootstrapper.NancyBootstrapperBase`1.get_AssemblyCatalog()
at Nancy.Bootstrapper.NancyBootstrapperBase`1.get_TypeCatalog()
at Nancy.Bootstrapper.NancyBootstrapperBase`1.GetInitializedInternalConfiguration()
at Nancy.Bootstrapper.NancyBootstrapperBase`1.Initialise()
at Nancy.Owin.NancyMiddleware.UseNancy(NancyOptions options)
at Nancy.Owin.DelegateExtensions.UseNancy(Action`1 builder, NancyOptions options)
at Microsoft.AspNetCore.Builder.OwinExtensions.UseOwin(IApplicationBuilder builder, Action`1 pipeline)
```

**Comment by thecodejunkie** [comment]
@andymac4182 hmm, yeah so it's kind of the same problem. Nancy needs to create an instance of `IAssemblyCatalog` (see [here](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/NancyBootstrapperBase.cs#L97), which on .NET Core is [DependencyContextAssemblyCatalog](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/DependencyContextAssemblyCatalog.cs)

In the constructor of `DependencyContextAssemblyCatalog` we do the following

```c#
public DependencyContextAssemblyCatalog()
{
    var entryAssembly = Assembly.GetEntryAssembly();
            
    this.dependencyContext = DependencyContext.Load(entryAssembly);
}
```

We do this in order to load the dependency context, of the main assembly of your application, in order to load the dependency context which is embedded in the assembly (it's put there by the `dotnet build` tool). We extract that file and build up a catalog of all assemblies that uses a Nancy type.

What you could try is to copy the code of `DependencyContextAssemblyCatalog`, create your own version of it, and replace the ctor with a hard-coded solution, something like

```c#
public DependencyContextAssemblyCatalog()
{
    var entryAssembly = typeof(SomeTypeInYourMainAssembly).Assembly;
            
    this.dependencyContext = DependencyContext.Load(entryAssembly);
}
```

And then _override_ [NancyBootstrapperBase.AssemblyCatalog](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Bootstrapper/NancyBootstrapperBase.cs#L90) to return an instance of your own version of `DependencyContextAssemblyCatalog`

Let me know how this works.

**Comment by andymac4182** [comment]
@thecodejunkie That works!! Thank you heaps for that. 

It would be great if there was a simple way to specify the main assembly from our side but this is a workable solution.

**Comment by thecodejunkie** [comment]
@andymac4182 great! I've just sent in #2694 to at least help make it a bit easier since there's no need to duplicate the entire class. once it's been pulled in. Would you be interested in helping us write a "Hosting on AWS Lambda" section on our wiki? We have a bunch of others

![image](https://cloud.githubusercontent.com/assets/50543/22408110/747b9aba-e673-11e6-926c-8b13f5badab3.png)

and I think adding an entry for AWS Lambda would be awesome

**Comment by damianh** [comment]
Alternative to using `Microsoft.AspNetCore.Builder.OwinExtensions.UseOwin`. Saves a message translation layer too!

https://github.com/damianh/Lancy/blob/master/src/Lancy/LancyProxyFunction.cs

**Comment by george-weare8** [comment]
> I just tried that and it fixed one error and now I get the below error.
> 
> ```
> An exception was thrown when the constructor for type 'PreviewAspNetCoreWebAPI.LambdaEntryPoint' was invoked. Check inner exception for more details.: LambdaException
> 
> 
> at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
> at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
> at System.Activator.CreateInstance(Type type, Boolean nonPublic)
> at System.Activator.CreateInstance(Type type)
> Exception has been thrown by the target of an invocation.: TargetInvocationException
> at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
> at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
> at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
> at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
> at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
> at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction..ctor()
> Value cannot be null.
> Parameter name: assembly: ArgumentNullException
> at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
> at Nancy.DependencyContextAssemblyCatalog..ctor()
> at Nancy.Bootstrapper.NancyBootstrapperBase`1.get_AssemblyCatalog()
> at Nancy.Bootstrapper.NancyBootstrapperBase`1.get_TypeCatalog()
> at Nancy.Bootstrapper.NancyBootstrapperBase`1.GetInitializedInternalConfiguration()
> at Nancy.Bootstrapper.NancyBootstrapperBase`1.Initialise()
> at Nancy.Owin.NancyMiddleware.UseNancy(NancyOptions options)
> at Nancy.Owin.DelegateExtensions.UseNancy(Action`1 builder, NancyOptions options)
> at Microsoft.AspNetCore.Builder.OwinExtensions.UseOwin(IApplicationBuilder builder, Action`1 pipeline)
> ```

@andymac4182 
Not related to NancyFx but I can't get assemblies when deploying in lambda, how did you fix this part?

```
List<Type> allAssembliesTypes = Assembly
                                    .GetEntryAssembly()
                                    .GetReferencedAssemblies()
                                    .Select(Assembly.Load)
                                    .SelectMany(a => a.GetTypes())
                                    .ToList();
```

**Comment by andymac4182** [comment]
You can't call `Assembly.GetEntryAssembly()` in lambda because its native code. You would be best to report lambda dotnet core deployment related issues in https://github.com/aws/aws-lambda-dotnet

**Comment by xplatsolutions** [comment]
Thank you for the answer @andymac4182. I will, do you by any chance know equivalent way to solve this?

**Comment by andymac4182** [comment]
Two options without going back through the code. Follow the instructions above about creating your own `DependencyContextAssemblyCatalog` or look at doing a self contained deployment with https://www.nuget.org/packages/Amazon.Lambda.RuntimeSupport/ 👍
