### ISSUE TITLE
UnobservedTaskException - System.ObjectDisposedException: Cannot access a disposed object when returning a StreamResponse

### ISSUE THREAD

**Issue by kimsagro1** [NancyFx/Nancy#2735]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of Nancy
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

We are constantly seeing the following exception in our logs when returning a `StreamResponse`
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
   at System.Net.HttpListenerResponse.CheckDisposed()
   at System.Net.HttpListenerResponse.set_StatusCode(Int32 value)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.SetStatusCode()
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.PrepareResponse(Boolean mayHaveBody)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.ResponseBodyStarted()
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.OnResponseBodyStarted(Object state)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.OneTimeCallback.TryInvoke()
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at Nancy.Responses.StreamResponse.<>c__DisplayClass1.<GetResponseBodyDelegate>b__0(Stream stream)
   at Nancy.Owin.NancyMiddleware.<>c__DisplayClasse.<RequestComplete>b__a(NancyContext context)
   at Nancy.NancyEngineExtensions.<>c__DisplayClass4.<HandleRequest>b__2(Task`1 t)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
   at System.Net.HttpListenerResponse.CheckDisposed()
   at System.Net.HttpListenerResponse.set_StatusCode(Int32 value)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.SetStatusCode()
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.PrepareResponse(Boolean mayHaveBody)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.ResponseBodyStarted()
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerResponse.OnResponseBodyStarted(Object state)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.OneTimeCallback.TryInvoke()
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at Nancy.Responses.StreamResponse.<>c__DisplayClass1.<GetResponseBodyDelegate>b__0(Stream stream)
   at Nancy.Owin.NancyMiddleware.<>c__DisplayClasse.<RequestComplete>b__a(NancyContext context)
   at Nancy.NancyEngineExtensions.<>c__DisplayClass4.<HandleRequest>b__2(Task`1 t)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

### Steps to Reproduce

Our application is capturing all `UnobservedTaskException`  (via ` TaskScheduler.UnobservedTaskException += UnobservedTaskException;`)

We have a module thats returning a `StreamResponse` containing a image

```csharp
private async Task<dynamic> SomeEndpoint(CancellationToken cancellationToken = default(CancellationToken))
{
    using (var someDisposable = new SomeDisposable())
    {
        // await something async
        return new StreamResponse(() => new MemoryStream(ImageByteArray), "image/png");
    }
}
```        

We are constantly seeing the above exception in out logs however it doesn't happen everytime

### System Configuration
We are self hosting nancy via owin in a windows service

- Nancy version:

```
  <package id="Nancy" version="1.4.3" targetFramework="net461" />
  <package id="Nancy.Bootstrappers.Autofac" version="1.4.1" targetFramework="net461" />
  <package id="Nancy.MSOwinSecurity" version="2.0.0" targetFramework="net461" />
  <package id="Nancy.Owin" version="1.4.1" targetFramework="net461" />
  <package id="Nancy.Serialization.JsonNet" version="1.4.1" targetFramework="net461" />
  ```

- Nancy host
  - [ ] ASP.NET
  - [X] OWIN
  - [X] Self-Hosted
  - [ ] Other:

**Comment by khellang** [comment]
What does `// await something async` mean?

**Comment by davidallyoung** [comment]
I'm going to guess on this one that the hot task SomeEndpoint() is being fired and doesn't complete before the rest of the request pipeline completes and starts clean up. Is the calling code actually awaiting this method call?

**Comment by khellang** [comment]
One more thing; why is `someDisposable` included in the snippet? I can't see it being used. This and the `// await something async` leads me to believe there are some important parts to this code being left out.

**Comment by michael-wolfenden** [comment]
Apologies for this issue being unclear.

To clarify:

The declaration looks like this

`Get["/some-endpoint/{id:guid}", runAsync: true] = async (context, token) => await SomeEndpoint(context.id, token);`

The code looks like this following

```csharp
private async Task<dynamic> SomeEndpoint(string id, CancellationToken cancellationToken = default(CancellationToken))
{
	// this body of the function is wrapped in a disposable logger
	// I included it in the code in-case wrapping the function within a disposable was potentially a cause of the issue
    using (var logger = new Logger())
    {
        // await something async
        // this comment was just to indicate that within this function I am calling some async methods, just in-case that
        // was important

        return new StreamResponse(() => new MemoryStream(ImageByteArray), "image/png");
    }
}
```

**Comment by kimsagro1** [comment]
Apologies for this issue being unclear.

To clarify:

The declaration looks like this

`Get["/some-endpoint/{id:guid}", runAsync: true] = async (context, token) => await SomeEndpoint(context.id, token);`

The code looks like this following

```csharp
private async Task<dynamic> SomeEndpoint(string id, CancellationToken cancellationToken = default(CancellationToken))
{
	// this body of the function is wrapped in a disposable logger
	// I included it in the code in-case wrapping the function within a disposable was potentially a cause of the issue
    using (var logger = new Logger())
    {
        // await something async
        // this comment was just to indicate that within this function I am calling some async methods, just in-case that
        // was important

        return new StreamResponse(() => new MemoryStream(ImageByteArray), "image/png");
    }
}
```

**Comment by kimsagro1** [comment]
Is there any more information you need that would help diagnose this issue?
