### ISSUE TITLE
Exception "Resolution of the dependency failed" while testing with custom bootstrapper

### ISSUE THREAD

**Issue by ghidosoft** [NancyFx/Nancy#2783]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of Nancy
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NancyFx/Nancy/issues) and [closed](https://github.com/NancyFx/Nancy/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm trying to run integration tests using Nancy 2.0.0-clinteastwood. When I run a test using the `Browser` class (using my boostrapper) I get this exception:

```
System.InvalidOperationException : Something went wrong when trying to satisfy one of the dependencies during composition, make sure that you've registered all new dependencies in the container and inspect the innerexception for more details.
  ----> Microsoft.Practices.Unity.ResolutionFailedException : Resolution of the dependency failed, type = "Nancy.INancyEngine", name = "(none)".
Exception occurred while: Calling constructor Nancy.Routing.RouteCache(Nancy.INancyModuleCatalog moduleCatalog, Nancy.INancyContextFactory contextFactory, Nancy.Routing.IRouteSegmentExtractor routeSegmentExtractor, Nancy.Routing.IRouteDescriptionProvider routeDescriptionProvider, Nancy.Culture.ICultureService cultureService, System.Collections.Generic.IEnumerable`1[[Nancy.Routing.IRouteMetadataProvider, Nancy, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]] routeMetadataProviders).
Exception is: ResolutionFailedException - Resolution of the dependency failed, type = "Nancy.INancyModule", name = "Nancy.Testing.ConfigurableNancyModule".
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The type String cannot be constructed. You must configure the container to supply this value.
-----------------------------------------------
At the time of the exception, the container was:

  Resolving Nancy.Testing.ConfigurableNancyModule,Nancy.Testing.ConfigurableNancyModule (mapped from Nancy.INancyModule, Nancy.Testing.ConfigurableNancyModule)
  Resolving parameter "modulePath" of constructor Nancy.Testing.ConfigurableNancyModule(System.String modulePath, System.Action`1[[Nancy.Testing.ConfigurableNancyModule+ConfigurableNancyModuleConfigurator, Nancy.Testing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]] closure)
    Resolving System.String,(none)

-----------------------------------------------
At the time of the exception, the container was:

  Resolving Nancy.NancyEngine,(none) (mapped from Nancy.INancyEngine, (none))
  Resolving parameter "dispatcher" of constructor Nancy.NancyEngine(Nancy.Routing.IRequestDispatcher dispatcher, Nancy.INancyContextFactory contextFactory, System.Collections.Generic.IEnumerable`1[[Nancy.ErrorHandling.IStatusCodeHandler, Nancy, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]] statusCodeHandlers, Nancy.Diagnostics.IRequestTracing requestTracing, Nancy.IStaticContentProvider staticContentProvider, Nancy.Responses.Negotiation.IResponseNegotiator negotiator, Nancy.Configuration.INancyEnvironment environment)
    Resolving Nancy.Routing.DefaultRequestDispatcher,(none) (mapped from Nancy.Routing.IRequestDispatcher, (none))
    Resolving parameter "routeResolver" of constructor Nancy.Routing.DefaultRequestDispatcher(Nancy.Routing.IRouteResolver routeResolver, System.Collections.Generic.IEnumerable`1[[Nancy.Responses.Negotiation.IResponseProcessor, Nancy, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]] responseProcessors, Nancy.Routing.IRouteInvoker routeInvoker, Nancy.Responses.Negotiation.IResponseNegotiator negotiator)
      Resolving Nancy.Routing.DefaultRouteResolver,(none) (mapped from Nancy.Routing.IRouteResolver, (none))
      Resolving parameter "routeCache" of constructor Nancy.Routing.DefaultRouteResolver(Nancy.INancyModuleCatalog catalog, Nancy.Routing.INancyModuleBuilder moduleBuilder, Nancy.Routing.IRouteCache routeCache, Nancy.Routing.Trie.IRouteResolverTrie trie, Nancy.Configuration.INancyEnvironment environment)
        Resolving Nancy.Routing.RouteCache,(none) (mapped from Nancy.Routing.IRouteCache, (none))
        Calling constructor Nancy.Routing.RouteCache(Nancy.INancyModuleCatalog moduleCatalog, Nancy.INancyContextFactory contextFactory, Nancy.Routing.IRouteSegmentExtractor routeSegmentExtractor, Nancy.Routing.IRouteDescriptionProvider routeDescriptionProvider, Nancy.Culture.ICultureService cultureService, System.Collections.Generic.IEnumerable`1[[Nancy.Routing.IRouteMetadataProvider, Nancy, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]] routeMetadataProviders)

  ----> Microsoft.Practices.Unity.ResolutionFailedException : Resolution of the dependency failed, type = "Nancy.INancyModule", name = "Nancy.Testing.ConfigurableNancyModule".
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The type String cannot be constructed. You must configure the container to supply this value.
-----------------------------------------------
At the time of the exception, the container was:

  Resolving Nancy.Testing.ConfigurableNancyModule,Nancy.Testing.ConfigurableNancyModule (mapped from Nancy.INancyModule, Nancy.Testing.ConfigurableNancyModule)
  Resolving parameter "modulePath" of constructor Nancy.Testing.ConfigurableNancyModule(System.String modulePath, System.Action`1[[Nancy.Testing.ConfigurableNancyModule+ConfigurableNancyModuleConfigurator, Nancy.Testing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]] closure)
    Resolving System.String,(none)

  ----> System.InvalidOperationException : The type String cannot be constructed. You must configure the container to supply this value.
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.SafeGetNancyEngineInstance()
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.GetEngine()
   at Nancy.Testing.Browser..ctor(INancyBootstrapper bootstrapper, Action`1 defaults)
   at RosettaServer.Spec.Integration.HomeSpec.<Home_ShouldShowHome>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
--ResolutionFailedException
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name, ResolverOverride[] resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)
   at Nancy.Bootstrappers.Unity.UnityNancyBootstrapper.GetEngineInternal()
   at Nancy.Bootstrapper.NancyBootstrapperBase`1.SafeGetNancyEngineInstance()
--ResolutionFailedException
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainer.<ResolveAll>d__6.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at Nancy.Routing.RouteCache.BuildCache(IEnumerable`1 modules)
   at Nancy.Routing.RouteCache..ctor(INancyModuleCatalog moduleCatalog, INancyContextFactory contextFactory, IRouteSegmentExtractor routeSegmentExtractor, IRouteDescriptionProvider routeDescriptionProvider, ICultureService cultureService, IEnumerable`1 routeMetadataProviders)
   at BuildUp_Nancy.Routing.RouteCache(IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuilderContext.NewBuildUp(NamedTypeBuildKey newBuildKey)
   at Microsoft.Practices.Unity.ObjectBuilder.NamedTypeDependencyResolverPolicy.Resolve(IBuilderContext context)
   at BuildUp_Nancy.Routing.DefaultRouteResolver(IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuilderContext.NewBuildUp(NamedTypeBuildKey newBuildKey)
   at Microsoft.Practices.Unity.ObjectBuilder.NamedTypeDependencyResolverPolicy.Resolve(IBuilderContext context)
   at BuildUp_Nancy.Routing.DefaultRequestDispatcher(IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuilderContext.NewBuildUp(NamedTypeBuildKey newBuildKey)
   at Microsoft.Practices.Unity.ObjectBuilder.NamedTypeDependencyResolverPolicy.Resolve(IBuilderContext context)
   at BuildUp_Nancy.NancyEngine(IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
--InvalidOperationException
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodConstructorStrategy.GuardTypeIsNonPrimitive(IBuilderContext context, SelectedConstructor selectedConstructor)
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodConstructorStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlanCreatorPolicy.CreatePlan(IBuilderContext context, NamedTypeBuildKey buildKey)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuilderContext.NewBuildUp(NamedTypeBuildKey newBuildKey)
   at Microsoft.Practices.Unity.ObjectBuilder.NamedTypeDependencyResolverPolicy.Resolve(IBuilderContext context)
   at BuildUp_Nancy.Testing.ConfigurableNancyModule(IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
```

### Steps to Reproduce
My test method is very simple, using nunit3:

```c#
[Test]
public async Task Home_ShouldShowHomepage()
{
    var bootstrapper = new TestBootstrapper();
    var browser = new Browser(bootstrapper); // <-- it crashes here
    var response = await browser.Get("/");
    Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
}
```

My `TestBootstrapper` class inherits from my custom boostrapper that inherits from `UnityNancyBootstrapper`. The application with the custom boostrapper runs fine in OWIN, it's only the integration test that's throwing exception. The `TestBootstrapper` simply use a `IRootPathProvider` to find views.

### System Configuration

- Nancy version: 2.0.0-clinteastwook
- Nancy host
  - [ ] ASP.NET
  - [x] OWIN
  - [ ] Self-Hosted
  - [ ] Other:
- Other Nancy packages and versions: Nancy.Bootstrapper.Unity, Nancy.Testing, Nancy.Validation.FluentValidation, Nancy.Serialization.JsonNet, Nancy.Authentication.Stateless+Forms, all 2.0.0-clinteastwood
- Environment (Operating system, version and so on): Windows 10, VS2017
- .NET Framework version: 4.6.1
- Additional information: Unity container, nunit3 tests

**Comment by ghidosoft** [comment]
I found a workaround: in my `TestBootstrapper` class I explicitly excluded the `ConfigurableNancyModule` module:

```c#
protected override IEnumerable<ModuleRegistration> Modules
{
  get {
    return base.Modules.Where(x => x.ModuleType != typeof(Nancy.Testing.ConfigurableNancyModule));
  }
}
```

**Comment by OlegMursalov** [comment]
Ok
