### ISSUE TITLE
'Nancy.Bootstrapper.AppDomainAssemblyTypeScanner' threw System.MissingMethodException: Method not found: 'System.AppDomainSetup System.AppDomain.get_SetupInformation()'

### ISSUE THREAD

**Issue by cinderell4** [NancyFx/Nancy#2819]
### Description
First steps with Nancy:

```
using System;
using Nancy.Hosting.Self;

namespace HelloNancy2
{
    class Program
    {
        static void Main(string[] args)
        {
            var url = "http://127.0.0.1:5000";
            using(var host = new NancyHost(new Uri(url)))
            {
                host.Start();
                Console.WriteLine("Nancy Server listening on {0}", url);
                Console.ReadLine();
            }
        }
    }
}
```
### Steps to Reproduce
Compile and Run results in:

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Nancy.Bootstrapper.AppDomainAssemblyTypeScanner' threw an exception. ---> System.MissingMethodException: Method not found: 'System.AppDomainSetup System.AppDomain.get_SetupInformation()'.
   at Nancy.Bootstrapper.AppDomainAssemblyTypeScanner.<GetAssemblyDirectories>d__37.MoveNext()
   at Nancy.Bootstrapper.AppDomainAssemblyTypeScanner.LoadAssembliesWithNancyReferences()
   at Nancy.Bootstrapper.AppDomainAssemblyTypeScanner..cctor()
   --- End of inner exception stack trace ---
   at Nancy.Bootstrapper.AppDomainAssemblyTypeScanner.TypesOf[TType](ScanMode mode)
   at Nancy.Bootstrapper.NancyBootstrapperLocator.GetBootstrapperType()
   at Nancy.Bootstrapper.NancyBootstrapperLocator.LocateBootstrapper()
   at Nancy.Bootstrapper.NancyBootstrapperLocator.get_Bootstrapper()
   at Nancy.Hosting.Self.NancyHost..ctor(Uri[] baseUris)

### System Configuration
- Nancy version: 1.4.4
- Nancy host
  - [X] Nancy.Hosting.Self 1.4.1
- Other Nancy packages and versions:
- Environment (Operating system, version and so on):
  - Ubuntu 16.10
- .NET Framework version:
  - Microsoft.NETCore.App/2.0.0
  - Microsoft.NETCore.Platforms/2.0.0
  - NETStadard.Library/2.0.0

**Comment by thecodejunkie** [comment]
Nancy 1.x does not run on .NET Core you need to use  `2.0-clienteastwood` to run on Core

**Comment by xmedeko** [comment]
@thecodejunkie  Any roadmap to merge `2.0-clienteastwood` to master?
